### ISSUE TITLE
Keyboard + Trackpad not working anymore after kernel update

### ISSUE THREAD

**Issue by geovie** [mikeeq/mbp-fedora-kernel#4]
Hi, again thanks for this project.
I had kernel version `5.3.15-300.mbp.fc31.x86_64` installed with the live cd of `mbp-fedora`.
After updating to kernel `5.4.8-200.mbp.fc31.x86_64` the keyboard and trackpad of the macbook are not working anymore, the external keyboard + mouse is working fine.

I've also tried updating to version `5.4.10-200.mbp.fc31.x86_64`, but keyboard and trackpad are also not working.

Macbook Pro 15,2 i5

Is anyone else having this problem?

**Comment by ktkd** [comment]
you should build kernel modules.
look at patch_driver.sh	and  patch_kernel_manually.sh.

**Comment by mikeeq** [comment]
Please use update_kernel_mbp script for updating kernel:
https://github.com/mikeeq/mbp-fedora-kernel/tree/v5.4-f31#how-to-update-kernel-mbp

Cheers!

**Comment by matsuhav** [comment]
Thank you for this project.

I installed mbp-fedora 5.4.
When I updated kernel from 5.4 to 5.5 and run `update_kernel_mbp`,
`sed` failed with ``sed: -e expression #1, char 54: unknown option to `s'``.

My `${GRUB_CMDLINE_VALUE}` was
`resume=/dev/mapper/fedora_localhost--live-swap rd.lvm.lv=fedora_localhost-live/root rd.lvm.lv=fedora_localhost-live/swap rhgb quiet`
It includes slashes and `sed` failed.

I changed `sed` command to use `:` as delimiter instead of `/` like
```
sed -i "s:^GRUB_CMDLINE_LINUX=.*:GRUB_CMDLINE_LINUX=\"${GRUB_CMDLINE_VALUE}\":g" /etc/default/grub
```
, everything is fine.
Can you update the script?

**Comment by mikeeq** [comment]
@matsuhav thanks for raising the issue, it's was fixed with recent commit ;)
